eureka:
  client:
    serviceUrl:
      #服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.1.66:8761/eureka/
server:
  #0 端口随机
  port: 0
spring:
  application:
    #服务与服务之间相互调用一般都是根据这个name
    name: redis-service
#Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
#    host: 192.168.1.66  #Redis服务器地址
    host: 127.0.0.1  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
    timeout:  0 # 连接超时时间（毫秒）

