eureka:
  client:
    serviceUrl:
#     服务注册中心的地址
      defaultZone: http://172.20.55.4:8761/eureka/
#为0 端口随机
server:
  port: 0

#zipkin
  zipkin:
    base-url: http://localhost:9411
spring:
  application:
#   服务与服务之间相互调用一般都是根据这个name
    name: user-service
  datasource:
      name: test
#     末尾useSSL=true：ssl是一种加密技术在客户端连接数据库的中间做了加密，TCP/IP层中
      url: jdbc:mysql://127.0.0.1:3306/xiaofangyuan?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
#      url: jdbc:mysql://rm-wz92a6yw952x0zgxnfo.mysql.rds.aliyuncs.com:3306/xiaofangyuan?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
      username: root
#      password: Xiaofangyuan123
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
#bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
    timeout:  0 # 连接超时时间（毫秒）
#max-file-size 单个数据大小限制
#max-request-size 总数据大小限制
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
  mvc:
    async:
      request-timeout: 30s
#springcloud-bus
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
  cloud:
    bus:
      trace:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangyuanyouyue.user.model

mapper:
  mappers:  com.fangyuanyouyue.user.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
##断路器开关
#feign:
#    hystrix:
#        enabled: true
##防止springboot2.0以上出现Unable to connect to Command Metric Stream
##默认其实的切入点是：/actuator/hystrix.stream 要改成/hystrix.stream
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#base-path: /
