#为0 端口随机
server:
  port: 0

#zipkin
  zipkin:
    base-url: http://localhost:9411
spring:
  profiles:
#    active: dev
#    active: test
    active: prod
#springcloud-bus

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
  cloud:
    bus:
      trace:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangyuanyouyue.forum.model
mapper:
  mappers:  com.fangyuanyouyue.forum.dao
  not-empty: false
  identity: MYSQL

#pagehelper分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check