#为0 端口随机
server:
  port: 0

#zipkin
  zipkin:
    base-url: http://localhost:9411
spring:
  profiles:
#    active: dev
    active: test
#springcloud-bus
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
  cloud:
    bus:
      trace:
        enabled: true