eureka:
  client:
    serviceUrl:
#     服务注册中心的地址
      defaultZone: http://192.168.1.66:8761/eureka/
spring:
  application:
  #   服务与服务之间相互调用一般都是根据这个name
      name: timer-service
#bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest